instrumentation:
    excludes:
        - "Chaincode/**"
        - "config/**"
        - "Client_Side/**"
        - "Documentation/**"
        - "Images/**"
        - "Local_Files/**"
        - "membersrvc/**"
        - "Scripts/**"
check:
    global:
        statements: 0
        branches: 0
        functions: 0
        lines: 0
